### ISSUE TITLE
CountryCodeSelector initializator doesn't make sense

### ISSUE THREAD

**Issue by michalcickan** [canopas/flutter-country-picker#1]
In this initializator in country_code_selector, assertion is wrong

CountryCodeSelector({
    super.key,
    this.scrollController,
    this.backgroundColor = Colors.white,
    required this.onCountryCodeTap,
    this.shape = const RoundedRectangleBorder(),
    this.customizationBuilders,
    this.countryNameLocale,
  }) : assert(
            onCountryCodeTap != null &&
                customizationBuilders?.codeBuilder != null,
            'Cannot provide both onCountryCodeTap and codeBuilder, as onCountryCodeTap will not work if you have provided codeBuilder.');

If onCountryCodeTap is null and customizationBuilders?.codeBuilder is null it asserts failure.

I would suggest assert like this:
 assert(
            (onCountryCodeTap != null &&
                customizationBuilders?.codeBuilder == null) || 
             (onCountryCodeTap == null &&
                customizationBuilders?.codeBuilder != null) || 
             (onCountryCodeTap == null &&
                customizationBuilders?.codeBuilder == null),
            'Cannot provide both onCountryCodeTap and codeBuilder, as onCountryCodeTap will not work if you have provided codeBuilder.');

**Comment by michalcickan** [comment]
Hello. I made a [pull request](https://github.com/canopas/flutter-country-picker/pull/2/commits/c00c3895fa6555d644de797abaa5f60a509ea7f0) for it.

**Comment by cp-pratik-k** [comment]
Hello @michalcickan, 
Thank you for reporting this issue. We have fixed it in a better version, and you can review it here.
[Assertion error fix](https://github.com/canopas/flutter-country-picker/pull/3)
