### ISSUE TITLE
+47 is parsed as Bouvet Island instead of Norway

### ISSUE THREAD

**Issue by larssn** [canopas/flutter-country-picker#7]
So Bouvet Island is an anomaly, and it actually has +47 as dial code, but when using `CountryCode.getCountryCodeByDialCode(dialCode: '+47');` you probably want it to find Norway 😄

**Comment by cp-pratik-k** [comment]
We'll research it and make some requirement changes ASAP.

**Comment by cp-pratik-k** [comment]
> So Bouvet Island is an anomaly, and it actually has +47 as dial code, but when using `CountryCode.getCountryCodeByDialCode(dialCode: '+47');` you probably want it to find Norway 😄

We'll research it and make some requirement changes ASAP.

**Comment by cp-pratik-k** [comment]
> So Bouvet Island is an anomaly, and it actually has +47 as dial code, but when using `CountryCode.getCountryCodeByDialCode(dialCode: '+47');` you probably want it to find Norway 😄

Thank you for sharing your feedback with us. We'll research it and make some requirement changes ASAP.

**Comment by larssn** [comment]
> Thank you for sharing your feedback with us. We'll research it and make some requirement changes ASAP.

Any progress on this?

**Comment by cp-pratik-k** [comment]
> > Thank you for sharing your feedback with us. We'll research it and make some requirement changes ASAP.
> 
> Any progress on this?

we've introduced a new method:
```
Dart
List<CountryCode> code = CountryCode.getCountryCodesByDialCode(
    dialCode: "+47",
);
```
This method returns a list of CountryCode objects, allowing you to handle multiple countries with the same dial code more effectively.

For more precise identification, we strongly recommend using the alpha-2 code, which is a two-letter country code that is unique to each country.

**Comment by larssn** [comment]
Thanks!
